[package]
name = "safety-profiler"
version = "0.1.0"
edition = "2024"

[dependencies]
safety-net = "0.14.0"
safety-pass = { version = "0.4.17", features = ["id"] }
nl-compiler = "0.3.2"
sv-parser = "0.13.4"
pprof = { version = "0.15.0", features = ["flamegraph", "criterion"], optional = true }
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "pipeline"
harness = false

[profile.release]
debug = 1

[profile.profiling]
inherits = "release"
debug = 2

[features]
flamegraph = ["dep:pprof"]